before_script:
  - gem install dpl

stages:
  - deploy

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - dpl --provider=heroku --app=$HEROKU_STAGING_APP --api-key=$HEROKU_API_KEY
  environment:
    name: staging
    url: https://hopenfamily-staging.herokuapp.com
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - echo "Deploy to production server"
    - dpl --provider=heroku --app=$HEROKU_PRODUCTION_APP --api-key=$HEROKU_API_KEY
  environment:
    name: production
    url: https://hopenfamily.herokuapp.com
  only:
    - tags
