source 'https://rubygems.org'
ruby '2.4.1'

gem 'devise'
gem 'devise-i18n'
gem 'draper'
gem 'figaro'
gem 'jbuilder', '~> 2.0'
gem 'pg'
gem 'puma'
gem 'pundit'
gem 'rails', '~> 5.0.0'
gem 'rails-i18n', '~> 5.0.0'
gem 'redis'
gem 'rest-client'

gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'bootstrap3-datetimepicker-rails'
gem 'cookies_eu'
gem 'font-awesome-sass'
gem 'jquery-rails'
gem 'momentjs-rails'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'
  gem 'listen', '~> 3.0.5'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
